// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./AboutSlice")),
  about_body: dynamic(() => import("./HomeSlice")),
  hero: dynamic(() => import("./HeroSlice")),
  paintings: dynamic(() => import("./PaintingSlice")),
  shop_slice: dynamic(() => import("./ShopSlice")),
};
