import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "@/style/globals.css";

const merri = Merriweather({
  variable: "--font-merri",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merri.variable} antialiased`}
      >
        <>
        <header>I'm the head</header>
        {children}
        <footer>I'm the footer</footer>
        </>
      </body>
    </html>
  );
}
